### ISSUE TITLE
The kbd driver does not compile on systems with kernel 6.x

### ISSUE THREAD

**Issue by hcdeeken** [ardangelo/beepberry-keyboard-driver#13]
I am trying to set up my beepy with Arch Linux ARM, using the files from https://github.com/DelusionalLogic/beepy-packages
The PKGBUILD file pulls in the git repository, so I am using the current source.

When the system tries build the module, I get two compile time errors (see attached make.log)

I sadly have no clue how to fix those.

Arch Linux ARM for Raspberry Pi comes out of the box with kernel 6.6.14 and I suspect that has something to do with the errors.

I know that Arch Linux is probably out of scope here, but sooner or later Raspbian will get newer kernels, so this is more or less future proofing ;)

[beepy-kbd-make.log](https://github.com/ardangelo/beepberry-keyboard-driver/files/14167604/beepy-kbd-make.log)

**Comment by hcdeeken** [comment]
Ah, I forgot to mention: this has worked in the past, some time ago. I sadly can't remember when exactly and which kernel and driver version it was.

**Comment by hcdeeken** [comment]
It seems as if kernel 6.1 is working, but 6.4 and higher is not. No idea yet about 6.2 or 6.3

**Comment by ih8ms** [comment]
Same here. Kernel 6.4 or even 6.6 (current Armbian 24.2) would be highly appreciated.

**Comment by ardangelo** [comment]
I've pushed updates for both the display and keyboard drivers for Linux 6.6. Please let me know if you have any issues with the updates.
