### ISSUE TITLE
Sticky modifier keys report key up before reporting the key they are modifying

### ISSUE THREAD

**Issue by gernb** [ardangelo/beepberry-keyboard-driver#14]
While coding the keyboard event handling for the Beepy port of PumpkinOS I discovered that the key up/down events reported on /dev/input/event0 are in the incorrect order. If I press and release the shift key (or the alt key or the sym key, etc) to turn on the “sticky bit” for that key, then the order of events when I press the modified key (like, for example, “w”) is:
* shift down
* w down
* shift up
* w up
The order should be:
* shift down
* w down
* w up
* shift up

I have to “work around” this behaviour by saving the modifier key state until after the modified key goes up:
https://github.com/gernb/PumpkinOS/blob/108024ce4cd8078460bdacfd36f837130dc8ab5b/src/libbeepy/libbeepy.c#L551

**Comment by ardangelo** [comment]
I tried out resetting the sticky modifier when a key is released, but this ends up applying it to all keys that are pressed in rapid succession. Typing moderately fast, it is easy to hit the speed where a sticky modifier will apply to two keys in a row. So unfortunately `modifier down - key down - modifier up - key up` is required.
