### ISSUE TITLE
key map overlay not work segmentation fault

### ISSUE THREAD

**Issue by chnjyxz** [ardangelo/beepberry-keyboard-driver#15]
Raspberry Pi Zero W  with 32-bit stock Raspbian
update, and install all packages in  Beepy PPA
I can see the sym icon overlays in the corner . 
but can't see key map overlay （hold [Berry] key or [sym]key）.
when running /sbin/symbol-overlay /dev/dri/card0 see segmentation fault .
need help ,thanks!

**Comment by ardangelo** [comment]
Working on it here,
https://github.com/ardangelo/beepy-gen/issues/5
