### ISSUE TITLE
Update for latest version of Raspbian

### ISSUE THREAD

**Issue by evanjrowley** [ardangelo/beepberry-keyboard-driver#4]
It would be wonderful if beepy-kbd and sharp-drm could be installed on the latest version of Raspbian. Right now it isn't working:
![Screenshot_20231026-214724_1](https://github.com/ardangelo/beepberry-keyboard-driver/assets/122766435/a94221f2-3865-47b8-8adc-f58359cbb984)

**Comment by cybernetikaIO** [comment]
Can also confirm this issue with current firmware image. Beepy instructions indicate using the most current image:
-  Choose OS - Raspberry Pi OS (other) - Raspberry Pi OS Lite (32-bit) image

Current Lite image is 2023-10-10 which apparently is incompatible with Beepy drivers provided in the beepy-ppa archive.

**Comment by KGOrphanides** [comment]
I encountered the same issue, documented with logs in an issue raised for the Beepy Docs at https://github.com/sqfmi/beepy-docs/issues/21

[bash-log.txt](https://github.com/ardangelo/beepberry-keyboard-driver/files/13308191/bash-log.txt)
[beepy-kbd-make.log](https://github.com/ardangelo/beepberry-keyboard-driver/files/13308192/beepy-kbd-make.log)

**Comment by ardangelo** [comment]
Hi all, I finally got back to this. I updated the packages to support changes in Debian 12, and they are working for me on both Debian 11 and 12 now. Please let me know if you are seeing any more problems.

**Comment by KGOrphanides** [comment]
Confirmed working, thank you.
